/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

/**
 *
 * @author user
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuario = new javax.swing.JMenu();
        mnuUsuarioIniciarSesion = new javax.swing.JMenuItem();
        mnuUsuarioCambiarUusuario = new javax.swing.JMenuItem();
        mnuUsuarioCambiarContraseña = new javax.swing.JMenuItem();
        mnuUsuarioCerrarSesion = new javax.swing.JMenuItem();
        mantenimiento = new javax.swing.JMenu();
        mnuMantenimientoUsuario = new javax.swing.JMenuItem();
        mnuMantenimientoProveedor = new javax.swing.JMenuItem();
        mnuMantenimientoCliente = new javax.swing.JMenuItem();
        mnuMantenimientoPropiedad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        reporte = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnuReporteVentas = new javax.swing.JMenuItem();
        mnuReporteDeudores = new javax.swing.JMenuItem();
        mnuReporteAquileres = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuReporteComprasAnuales = new javax.swing.JMenuItem();
        mnuReporteIngresos = new javax.swing.JMenuItem();
        mnuReporteEmpleadoMes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        usuario.setText("Usuario");

        mnuUsuarioIniciarSesion.setText("Iniciar Sesión");
        mnuUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioIniciarSesionActionPerformed(evt);
            }
        });
        usuario.add(mnuUsuarioIniciarSesion);

        mnuUsuarioCambiarUusuario.setText("Cambiar Usuario");
        mnuUsuarioCambiarUusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioCambiarUusuarioActionPerformed(evt);
            }
        });
        usuario.add(mnuUsuarioCambiarUusuario);

        mnuUsuarioCambiarContraseña.setText("Cambiar Contraseña");
        mnuUsuarioCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioCambiarContraseñaActionPerformed(evt);
            }
        });
        usuario.add(mnuUsuarioCambiarContraseña);

        mnuUsuarioCerrarSesion.setText("Cerrar Sesión");
        usuario.add(mnuUsuarioCerrarSesion);

        jMenuBar1.add(usuario);

        mantenimiento.setText("Mantenimiento");

        mnuMantenimientoUsuario.setText("Usuario");
        mnuMantenimientoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMantenimientoUsuarioActionPerformed(evt);
            }
        });
        mantenimiento.add(mnuMantenimientoUsuario);

        mnuMantenimientoProveedor.setText("Proveedor");
        mnuMantenimientoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMantenimientoProveedorActionPerformed(evt);
            }
        });
        mantenimiento.add(mnuMantenimientoProveedor);

        mnuMantenimientoCliente.setText("Cliente");
        mnuMantenimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMantenimientoClienteActionPerformed(evt);
            }
        });
        mantenimiento.add(mnuMantenimientoCliente);

        mnuMantenimientoPropiedad.setText("Propiedad");
        mnuMantenimientoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMantenimientoPropiedadActionPerformed(evt);
            }
        });
        mantenimiento.add(mnuMantenimientoPropiedad);

        jMenuBar1.add(mantenimiento);

        jMenu4.setText("Operaciones");

        jMenu5.setText("Ventas");

        jMenuItem1.setText("Gestionar Venta");
        jMenu5.add(jMenuItem1);

        jMenuItem3.setText("Buscar Venta");
        jMenu5.add(jMenuItem3);

        jMenuItem8.setText("Gestionar Pago");
        jMenu5.add(jMenuItem8);

        jMenuItem7.setText("Registrar Pago");
        jMenu5.add(jMenuItem7);

        jMenu4.add(jMenu5);

        jMenu6.setText("Compras");

        jMenuItem2.setText("Gestionar una Compra");
        jMenu6.add(jMenuItem2);

        jMenuItem4.setText("Buscar Compra");
        jMenu6.add(jMenuItem4);

        jMenu4.add(jMenu6);

        jMenu7.setText("Cliente");

        jMenuItem5.setText("Gestionar Cliente");
        jMenu7.add(jMenuItem5);

        jMenuItem6.setText("Buscar Cliente");
        jMenu7.add(jMenuItem6);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        reporte.setText("Reportes");

        jMenu1.setText("Ventas");

        mnuReporteVentas.setText("Listar ventas por mes");
        jMenu1.add(mnuReporteVentas);

        mnuReporteDeudores.setText("Listar clientes deudores");
        jMenu1.add(mnuReporteDeudores);

        mnuReporteAquileres.setText("Listar alquileres mensuales");
        jMenu1.add(mnuReporteAquileres);

        reporte.add(jMenu1);

        jMenu2.setText("Compras");

        mnuReporteComprasAnuales.setText("Compras Anuales");
        jMenu2.add(mnuReporteComprasAnuales);

        reporte.add(jMenu2);

        mnuReporteIngresos.setText("Ingresos mensuales");
        reporte.add(mnuReporteIngresos);

        mnuReporteEmpleadoMes.setText("Empleado del mes");
        reporte.add(mnuReporteEmpleadoMes);

        jMenuBar1.add(reporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuarioCambiarUusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioCambiarUusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuarioCambiarUusuarioActionPerformed

    private void mnuUsuarioCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioCambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuarioCambiarContraseñaActionPerformed

    private void mnuMantenimientoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMantenimientoProveedorActionPerformed
        // TODO add your handling code here:
        jdProveedor objProveedor = new jdProveedor(this, true);
        objProveedor.setVisible(true);
        objProveedor.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuMantenimientoProveedorActionPerformed

    private void mnuMantenimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMantenimientoClienteActionPerformed
        // TODO add your handling code here:
        jdCliente objCliente = new jdCliente(this, true);
        objCliente.setVisible(true);
        objCliente.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuMantenimientoClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jdLogin objIniciar = new jdLogin(this,true);
        objIniciar.setLocationRelativeTo(this);
        objIniciar.setVisible(true);
        usuario.setText(objIniciar.nombre);
    }//GEN-LAST:event_formWindowOpened

    private void mnuUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuarioIniciarSesionActionPerformed

    private void mnuMantenimientoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMantenimientoUsuarioActionPerformed
        // TODO add your handling code here:
        jdUsuario objUsuario = new jdUsuario(this, true);
        objUsuario.setVisible(true);
        objUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuMantenimientoUsuarioActionPerformed

    private void mnuMantenimientoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMantenimientoPropiedadActionPerformed
        // TODO add your handling code here:
        jdPropiedad objPropiedad = new jdPropiedad(this, true);
        objPropiedad.setVisible(true);
        objPropiedad.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuMantenimientoPropiedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mantenimiento;
    private javax.swing.JMenuItem mnuMantenimientoCliente;
    private javax.swing.JMenuItem mnuMantenimientoPropiedad;
    private javax.swing.JMenuItem mnuMantenimientoProveedor;
    private javax.swing.JMenuItem mnuMantenimientoUsuario;
    private javax.swing.JMenuItem mnuReporteAquileres;
    private javax.swing.JMenuItem mnuReporteComprasAnuales;
    private javax.swing.JMenuItem mnuReporteDeudores;
    private javax.swing.JMenuItem mnuReporteEmpleadoMes;
    private javax.swing.JMenuItem mnuReporteIngresos;
    private javax.swing.JMenuItem mnuReporteVentas;
    private javax.swing.JMenuItem mnuUsuarioCambiarContraseña;
    private javax.swing.JMenuItem mnuUsuarioCambiarUusuario;
    private javax.swing.JMenuItem mnuUsuarioCerrarSesion;
    private javax.swing.JMenuItem mnuUsuarioIniciarSesion;
    private javax.swing.JMenu reporte;
    private javax.swing.JMenu usuario;
    // End of variables declaration//GEN-END:variables
}
